# Generated by Django 2.0.5 on 2018-05-13 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='The title of this web page.', max_length=50, null=True)),
                ('goal', models.CharField(blank=True, help_text='The communication goal that this page seeks to achieve.', max_length=200, null=True)),
                ('filename', models.CharField(blank=True, help_text='The file that will be written out when this page is rendered.', max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_creater', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, help_text='The heading (if any) for this section.', max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('fs', 'Full Section'), ('cs', 'Column Section'), ('is', 'Image Section')], help_text='The type of section this is.', max_length=2, null=True)),
                ('text', models.TextField(help_text='The text of this web page section.  This may contain HTML tags for extra styling')),
                ('icon', models.CharField(blank=True, help_text='The icon (Materialize) to go with this section.', max_length=5, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_creater', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_modifier', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_section', to='pages.Page')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
