# Generated by Django 2.0.5 on 2018-05-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, help_text='The URL that will point to this page in the current directory structure, once the static file is rendered.', max_length=200, null=True),
        ),
    ]
