# Generated by Django 2.0.5 on 2018-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_abbrv',
            field=models.CharField(blank=True, help_text='The abbreviation that will be used in navigation components for this page.', max_length=50, null=True),
        ),
    ]
